"""Public-accountability artifacts served straight from the API.

- transparency_record(): a UK Algorithmic Transparency Recording Standard (ATRS) record,
  the format central-government bodies must publish for citizen-facing algorithmic tools.
- model_card(): a Model Card (Mitchell et al. 2019) including explicit out-of-scope uses.

These make Tributo legible to a regulator, not just a user — the accountability half of the
track question.
"""

from __future__ import annotations

from .config import get_settings


def transparency_record() -> dict:
    s = get_settings()
    return {
        "standard": "UK Algorithmic Transparency Recording Standard (ATRS)",
        "tier_1": {
            "name": "Tributo — citizen tax guidance assistant",
            "description": (
                "A voice-first assistant that answers UK citizens' tax questions with plain-English "
                "guidance grounded in published GOV.UK / HMRC sources. It signposts and explains; it "
                "does not make tax determinations or file anything."
            ),
            "website": "https://github.com/your-org/tributo",
            "contact_email": "tributo-accountability@example.org",
            "phase": "pilot / hackathon prototype",
            "region": "United Kingdom",
        },
        "tier_2": {
            "owner_and_responsibility": {
                "process_owner": "Pilot deploying institution (e.g. a local council or Citizens Advice).",
                "responsible_for_decision": "A human caseworker — the tool never decides a citizen's tax position.",
                "external_supplier": "FLock (inference via the FLock API Platform); models are open-source.",
            },
            "description_and_rationale": {
                "how_it_works": (
                    "Speech-to-text → PII redaction → retrieval over a GOV.UK/HMRC corpus → grounded, "
                    "cited answer generated by an open-source model on the FLock API Platform → "
                    "text-to-speech. Every answer cites its sources and is written to an audit log."
                ),
                "rationale": (
                    "Professional tax advice is expensive and HMRC channels are overwhelmed; the people "
                    "who most need help are the least well served. Tributo widens access while keeping "
                    "the citizen's data private and every answer accountable."
                ),
                "alternatives_considered": "Sending raw questions to a centralised US cloud LLM (rejected on privacy grounds).",
            },
            "decision_making_process": {
                "human_in_the_loop": True,
                "escalation": "High-stakes, unsafe, or unsupported questions are escalated to a human adviser instead of answered.",
                "citizen_facing_explanation": "Each answer shows its sources, a confidence label, and a disclaimer that it is guidance, not a determination.",
            },
            "tool_specification": {
                "model_provider": "FLock API Platform",
                "model": s.flock_model,
                "model_type": "open-source large language model, OpenAI-compatible inference",
                "retrieval": f"{s.retriever} over a curated GOV.UK / HMRC corpus, with enforced inline citations",
                "pii_handling": "Personal identifiers redacted before inference; raw text not retained.",
                "federated_improvement": "Model improvements trained via federated learning (FedAvg); raw citizen data never leaves a node.",
            },
            "data": {
                "training_data_for_inference": "Open-source base model; no citizen data used to train it.",
                "federated_fine_tuning_data": "Per-institution anonymised Q&A held locally at each node; never centralised.",
                "data_retention": "No raw questions retained. The audit log stores only the redacted question and provenance.",
                "data_residency_note": (
                    "Federated training keeps data in-jurisdiction on local hardware. The hosted "
                    "inference API's physical region is not disclosed by the provider, which is why PII "
                    "is redacted before any text is sent."
                ),
            },
            "risks_mitigations_and_impact": {
                "risk_wrong_answer": "Mitigated by RAG grounding, enforced citations, confidence labels, and human escalation.",
                "risk_privacy": "Mitigated by pre-inference PII redaction and no raw-text retention.",
                "risk_over_trust": "Mitigated by visible disclaimers and a hard 'speak to a human' path below a confidence threshold.",
                "risk_bias_exclusion": "Accessibility-first (voice + extra-support signposting) to serve low digital-confidence users.",
                "impact_assessment": "DPIA recommended before any live deployment with real citizen data.",
            },
        },
    }


def model_card() -> dict:
    s = get_settings()
    return {
        "model_details": {
            "name": "Tributo tax-guidance pipeline",
            "version": "0.1.0 (hackathon prototype)",
            "base_model": s.flock_model,
            "provider": "FLock API Platform (open-source model, OpenAI-compatible)",
            "architecture": "RAG: retrieval over a GOV.UK/HMRC corpus + grounded generation, with PII redaction and guardrails.",
            "improvement": "Optional federated fine-tuning (FedAvg over LoRA adapters) across institution nodes.",
        },
        "intended_use": {
            "primary_uses": [
                "Explain UK tax concepts and deadlines to citizens in plain English.",
                "Signpost the relevant GOV.UK / HMRC guidance and a human adviser when needed.",
            ],
            "primary_users": "Self-employed, gig workers, first-time Self Assessment filers, people with accessibility or literacy needs.",
        },
        "out_of_scope_uses": [
            "Giving definitive or binding tax/legal determinations.",
            "Filing or submitting anything to HMRC.",
            "Advising on tax avoidance, evasion, or concealment of income.",
            "Processing real personal data in this prototype (synthetic personas only).",
        ],
        "factors": {
            "relevant_factors": "Plain-English readability; UK tax year specificity; accessibility for voice and low-literacy users.",
            "evaluation_factors": "Whether answers are grounded in and cited to retrieved sources.",
        },
        "metrics": {
            "answer_grounding": "Every factual claim must carry a [S#] citation to a retrieved source.",
            "escalation_rate": "Share of high-stakes/unsupported questions routed to a human.",
            "federated_improvement": "Before/after accuracy of the federated model on a held-out test set.",
        },
        "evaluation_data": "A fixed set of synthetic UK-tax questions spanning registration, deadlines, payments, expenses, rates, and penalties.",
        "training_data": "Inference base model is open-source. Federated fine-tuning uses per-institution anonymised, locally-held Q&A.",
        "ethical_considerations": (
            "Tax questions expose highly sensitive data. PII is redacted before inference and never "
            "retained; decisions affecting a citizen remain with an accountable human."
        ),
        "caveats_and_recommendations": (
            "Prototype for a hackathon. Run a DPIA and a fuller accuracy evaluation, and confirm the "
            "inference provider's data residency, before any deployment with real citizen data."
        ),
    }
